spring.application.name=project

SPRING_DATASOURCE_URL=jdbc:mysql://switchback.proxy.rlwy.net:52365/railway
SPRING_DATASOURCE_USERNAME=root
SPRING_DATASOURCE_PASSWORD=your_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
