spring.application.name=project

# Disable database completely
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Railway dynamic port (IMPORTANT)
server.port=${PORT:8080}
