spring.application.name=project 
spring.datasource.url=jdbc:mysql://root:xvKrhBmKcBOAzaobrrChhrngZkRHmDDa@switchback.proxy.rlwy.net:52365/railway
spring.datasource.username=root 
spring.datasource.password=xvKrhBmKcBOAzaobrrChhrngZkRHmDDa
spring.jpa.hibernate.ddl-auto=update spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration 
server.port=8081
